config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get "u/:username" => "public#profile", as: :profile
  resources :communities do
    resources :posts
  end
  resources :subscriptions
  resources :comments, only: [:create]

  post "post/vote" => "votes#create"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root to: "public#index"
end

app/models/account.rb
class Account < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :validatable

	has_many :subscriptions
	has_many :communities, through: :subscriptions
	has_many :posts
	has_many :comments
	has_many :votes

	validates_presence_of :first_name, :last_name, :username

	def full_name
		"#{first_name} #{last_name}"
	end

	def upvoted_post_ids
		self.votes.where(upvote: true).pluck(:post_id)
	end

	def downvoted_post_ids
		self.votes.where(upvote: false).pluck(:post_id)
	end
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :account

    validates_presence_of :message, :account_id, :post_id
    
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :account
  validates_presence_of :url, :name, :rules
  has_many :posts
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions, source: :account
 end
 

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :account
    belongs_to :community
    has_many :comments
    validates_presence_of :title, :body, :account_id, :community_id

    def score
    # difference between upvotes and downvotes
        if self.upvotes > 0 || self.downvotes > 0
            self.upvotes > 0 ? (self.upvotes - self.downvotes) : (self.downvotes * -1)
            else 
            0
        end

    end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    belongs_to :account
    belongs_to :community    
end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :account
    belongs_to :post

    validates_uniqueness_of :account_id, scope: :post_id

    after_create :increment_vote, :add_karma
    after_destroy :decrement_vote, :remove_karma

    private

    def increment_vote
        field = self.upvote ? :upvotes :  :downvotes
        Post.find(self.post_id).increment(field).save
    end

    def decrement_vote
        field = self.upvote ? :upvotes :  :downvotes
        Post.find(self.post_id).decrement(field).save
    end

    def add_karma
        account = Account.find(self.account_id)
        account.increment(:karma, 1).save
    end

    def add_karma
        account = Account.find(self.account_id)
        account.decrement(:karma, 1).save
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create 
        @comment = Comment.new comment_params
        @comment.account_id = current_account.id

     respond_to do |format|
      format.js {
        if @comment.save
            @comments = Comment.where(post_id: @comment.post_id)
            render "comments/create"
        else
            #unable to save
        end
      }
        end
    end

    def comment_params
        params.require(:comment).permit(:message, :post_id)
    end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_account!, expect: [:index, :show]
  before_action :set_community, only: [:show]


  def index
    @communities = Community.all
  end

  def show
    @posts = @community.posts.limit(20).sort_by{ |p| p.score }.reverse
    @subscriber_count = @community.subscribers.count
    @is_subscribed = account_signed_in? ? Subscription.where(community_id: @community.id, account_id: current_account.id).any? : false
    @subscription = Subscription.new
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new community_values
    @community.account_id = current_account.id

    if @community.save
      redirect_to communities_path
    else
      render :new
    end
  end


  private

  def set_community
    @community = Community.find(params[:id])
  end

  def community_values
    params.require(:community).permit(:name, :url, :rules, :summary)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, expect: [:index, :show]
  before_action :set_post, only: [:show]
  before_action :auth_subscriber, only: [:new]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @community = Community.find(params[:community_id])
    @post = Post.new
  end

  def create
    @post = Post.new post_values
    @post.account_id = current_account.id
    @post.community_id = params[:community_id]

    if @post.save
      redirect_to community_path(@post.community_id)
    else
    @community = Community.find(params[:community_id])
    render :new
    end
  end


  private

  def set_post
    @post = Post.includes(:comments).find(params[:id])
  end

  def auth_subscriber
   unless Subscription.where(community_id: params[:community_id], account_id: current_account.id).any? 
    redirect_to root_path, flash: { danger: "you are not authorized to view this post"}
   end
  end

  def post_values
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  def index
    @communities = Community.all.limit(5)
    @posts = Post.limit(20).sort_by{ |p| p.score }.reverse
    @vote = Vote.new
  end

  def profile
  @profile = Account.find_by_username params[:username]
  @posts = @profile.posts
  end
  
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

 def create 
    @subscription = Subscription.new(subscription_params)
    @subscription.account_id = current_account.id
    @subscription.save
       
    redirect_to community_path(@subscription.community_id)
 end

 def subscription_params
    params.require(:subscription).permit(:community_id)
 end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
    def create 
        post_id = params[:post_id]
        vote = Vote.new
        vote.post_id = params[:post_id]
        vote.upvote = params[:upvote]
        vote.account_id = current_account.account_id
    
        #check if the vote by this user exists
        existing_vote = Vote.where(account_id: current_account.id, post_id: params[:vote][:post_id])
        @new_vote = existig_vote.size < 1
    
respond_to do |format|
    format.js { 
        if existing_vote.size > 0
            # destroy existig vote
            existig_vote.first.destroy
        else 
        # save new vote
            if vote.save
                @success = true
            else 
                 @success = false
            end  
        end
        @post = Post.find(post_id)
        @is_upvote = params[:upvote]
        render "votes/create"
    }
    end
end    


    private 
    def vote_params
        params.require(:vote).permit(:upvote, :post_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/votes_helper.rb
module VotesHelper

   def is_upvoted post
       account_signed_in? && current_account.upvoted_post_ids.include?(post.id) ? " active" : ""
    end

    def is_downvoted post
        account_signed_in? && current_account.downvoted_post_ids.include?(post.id) ? " active" : "" 
    end
end

app/views/comments/create.js.erb
console.log("comment created...");

document.getElementById("#post-comments").innerHTML = "<%= escape_javascript(render partial: 'posts/comments', locals: {comments: @comments }) %>";

app/views/communities/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for @community do |form| %>
    <div class="form-group">
      <%= label_tag :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= label_tag :url %>
      <%= form.text_field :url, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= label_tag :summary %>
      <%= form.text_field :summary, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= label_tag :rules %>
      <%= form.text_area :rules, class: "form-control" %>
    </div>

    <%= form.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/communities/_subscribe.html.erb
<%= form_for @subscription do |f| %>
    <%= f.hidden_field :community_id, value: community_id %>
    <%= f.submit "Join Community", class:"btn btn-success text-uppercase float-right"%>
<% end %>  

app/views/communities/index.html.erb
<% if account_signed_in? %>
<div class="float-right">
  <%= link_to "Create New Community", new_community_path, class: "btn  btn-outline-primary" %>
</div>
<% end %>

<% if @communities.size > 0 %>
<%= @communities.each do |community| %>
<div class="card">
  <h3><%= link_to community.name, community  %></h3>
  <%= simple_format community.rules %>
</div>
<% end %>

<% else %>
<p>No communities to display.</p>
<% end %>

app/views/communities/new.html.erb
<h2>New Community</h2>

<%= render partial: "form" %>

app/views/communities/show.html.erb
 <div class="row mb-4">
	<div class="col-sm-8">
	 <h3><%= @community.name %></h3>
	</div>
    <div class="col-sm-4">
	<% if @is_subscribed  %>
	<%= link_to "Create New Post", new_community_post_path(@community), class: "btn btn-primary float-right" %>
	<% else %>
	 <%= render partial: "communities/subscribe", locals: { community_id: @community.id }%> 
	<% end %>
	</div>
</div>
 <div class="row">
    <div class="col-sm-8">
	 <%= render partial: "posts/list", locals: {posts: @posts}%>
</div>
<div class="col-sm-4">
	<div class="card p-3">
	<p class="h5">About this community </p>
	<p class="mt-2"><%= @community.summary %></p>
	
	<p><%= pluralize @subscriber_count, "member" %></p>
	</div>
	
	<small>
		<%= simple_format @community.rules %>
	</small>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 pt-3 pb-3">
      <div class="float-right">
      <% if account_signed_in? %>
        <div class="dropdown show float-right">
          <a class="btn btn-white dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_account.full_name %>
          </a>

<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
      <%= link_to "Profile", profile_path(current_account.username),  class: "dropdown-item" %>
      <%= link_to "Setting", edit_account_registration_path, class: "dropdown-item" %>
      <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "dropdown-item" %>
  </div>
</div> 
    <div class="karam float-left mt-2">
      <%= current_account.karma %>
      <span class="fa fa-star text-warning"></span>
    </div>
      <% else %>
      <%= link_to "Log In", new_account_session_path, class: "btn btn-outline-primary" %>
      <%= link_to "Sign Up", new_account_registration_path, class: "btn btn-outline-primary" %>
      <% end %>
    </div>
    <p class="h3"><%= link_to "Diskos", root_path %></p>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diskos</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
  <script src="https://kit.fontawesome.com/2d5097f6b3.js" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
</head>

<body>
  <%= render partial: "layouts/header" %>
<section class="bg-light">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 pt-4">
        <%= yield %>
      </div>
    </div>
  </div>
</section>

  <%= render partial: "layouts/footer" %>
</body>
</html>

app/views/posts/_comments.html.erb
<% comments.each do |comment| %>
<div class="comment">
    <%= link_to comment.account.full_name , profile_path(comment.account.username)%>
    <%= simple_format comment.message %>
</div>
<% end %> 

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for [@community, @post] do |form| %>
    <div class="form-group">
      <%= label_tag :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= label_tag :body %>
      <%= form.text_area :body, class: "form-control" %>
    </div>

    <%= form.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/_list.html.erb
<% posts.each do |post| %>
<div class="card p-3 mb-3">
    <div class="row">
     <div class="col-1 text-center">
     <div class="vote-actions-<%= post.id %>" class="vote" data-id="<%= post.id %>">
     <div class="fa fa-arrow-up upvote <%= is_upvoted post %>%"></div>
        <span class="font-weight-bold score"><%= post.score %></span>
        <div class="fa fa-arrow-down downvote <%= is_downvoted post %>%"></div>
      </div>   
     </div>
        <div class="col-11">
         <h4 class="mb-1"><%= link_to post.title, community_post_path(post.community_id, post)%> </h4>
         <p><small><%= link_to post.community.name, community_path(post.community) %> Posted by <%= link_to post.account.full_name, profile_path(post.account.username) %> <%= time_ago_in_words post.created_at %>ago.</small></p>
         <p><%= truncate post.body, length: 200%></p>
        </div>
    </div>
 </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Community</h2>

<%= render partial: "form" %>

app/views/posts/new.html.erb
<h2>New Community</h2>

<%= render partial: "form" %>

app/views/posts/show.html.erb
<div class="row">
 <div class="col-1 text-center">
     <div class="vote-actions-<%= @post.id %>" class="vote" data-id="<%= @post.id %>">
     <div class="fa fa-arrow-up upvote <%= is_upvoted @post %>%"></div>
        <span class="font-weight-bold score"><%= @post.score %></span>
        <div class="fa fa-arrow-down downvote <%= is_downvoted @post %>%"></div>
      </div>   
     </div>
<div class="col-11">
<h2> <%= @post.title %> </h2>

<%= simple_format @post.body %>

<div id="post-comments">
<%= render partial: "posts/comments", locals: { comments: @post.comments } %>
</div>

<h5>Leave a comment<h5>
<%= form_for @comment, remote: true do |f| %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.text_area :message, placeholder: "Your comment goes here", class: "form-control"  %>
    <%= f.submit "Submit comment", class: "btn btn-success mt-3"%>
<% end %>
</div>
</div>

app/views/votes/create.js.erb
//update total votes on view for post 
$("#vote-actions-<%= @post.id %> .score").text("<%= @post.score %>");

$("#vote-actions-<%= @post.id%> .downvote, #vote-actions-<%= @post.id %> .upvote").removeClass("active");

<% if @new_vote %>
<% if @is_upvote ==  "true" %>
$("#vote-actions-<%= @post.id %> .upvote").addClass("active");
<% else %>
$("#vote-actions-<%= @post.id %> .downvote").addClass("active");
<% end %>
<% end %>